defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: gmaps_mongo-development
  host: localhost
  logger: mongo

test: &test
  <<: *defaults
  database: gmaps_mongo-test
  host: localhost

cucumber:
  <<: *test

qa:
  <<: *defaults
  database: gmaps_mongo-qa
  host: localhost

production:
  <<: *defaults
  database: gmaps_mongo-development
  host: localhost

